### ISSUE TITLE
Move execution to somewhere more permanent

### ISSUE THREAD

**Issue by JohnGarnham** [ViNo-community/nano_node_bot#1]
Right now I am running the bot script from my personal laptop, which means that it's only available when my laptop is connected to the internet and I have the script currently running. Will need to move the script to somewhere more permanent for bot to always be available. Discuss options with team - VPS?

**Comment by Gabrielpatrola** [comment]
Here, send me a message in discord when you have time.

We can set the bot in the nano node server

**Comment by Gabrielpatrola** [comment]
Closing this issue as the service is already moved to a vps
