### ISSUE TITLE
Add auto-generation of invite link to make it easy for users to add to their own Discord servers

### ISSUE THREAD

**Issue by JohnGarnham** [ViNo-community/nano_node_bot#4]
Make a command to auto-generate an invite link to make it easy for users to add the nano_node_bot to their own servers. Users will just have to write !invite and the bot will auto-generate a URL for them that will automatically set up the bot for their server. 

Model after TweetShift's bot: t!invite

**Comment by JohnGarnham** [comment]
URL format: https://discord.com/oauth2/authorize?client_id=<client_id>&permissions=<permissions_integer>

**Comment by JohnGarnham** [comment]
Auto-generating URL is now available with !invite command.

**Comment by Gabrielpatrola** [comment]
Since it is already working, I'm closing this issue.

Great job @JohnGarnham 🥳
