### ISSUE TITLE
Add command that gets list of all delegator addresses & balances

### ISSUE THREAD

**Issue by ElemontCapital** [ViNo-community/nano_node_bot#5]
Add command that gets list of all delegator addresses & balances

**Comment by Gabrielpatrola** [comment]
If no one is doing it, I'm up to make it

**Comment by ElemontCapital** [comment]
> If no one is doing it, I'm up to make it

Go for it!
If you get stuck I'll get someone to help

**Comment by JohnGarnham** [comment]
Added !delegators command, but still need to chunk up big lists. Current list of delegators is too big for one send to Discord, need to split it up into smaller chunks.

**Comment by JohnGarnham** [comment]
Added !delegators command to show list of accounts and balances. Paginates list if message is too big for Discord (limit: 2000 chars).
